---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calico-exporter.fullname" . }}-ippool
  labels:
    {{- include "calico-exporter.ippool-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ippoolService.type }}
  ports:
    - name: https-metrics
      port: {{ .Values.ippoolService.port }}
      targetPort: {{ .Values.ippoolService.targetPort }}
  selector:
    {{- include "calico-exporter.ippool-collector.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calico-exporter.fullname" . }}-ipam
  labels:
    {{- include "calico-exporter.kube-controllers.labels" . | nindent 4 }}
  namespace: kube-system
spec:
  type: {{ .Values.calicoService.type }}
  ports:
    - name: http-metrics
      port: {{ .Values.calicoService.port }}
      targetPort: {{ .Values.calicoService.targetPort }}
  selector:
    {{- include "calico-exporter.kube-controllers.selectorLabels" . | nindent 4 }}