global:
  ## Global image registry to use if it needs to be overriden for some specific use cases (e.g local registries, custom images, ...)
  ##
  imageRegistry: ""

  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"
  # or
  # - "image-pull-secret"

namespaceOverride: kubesphere-monitoring-system

alertmanager:
  alertmanagerSpec:
    image:
      registry: quay.io
      repository: prometheus/alertmanager
      tag: v0.24.0 
    replicas: 1 
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 20m
        memory: 30Mi

prometheus:
  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v2.40.5
    replicas: 1
    resources:
      limits:
        cpu: "4"
        memory: 16Gi
      requests:
        cpu: 200m
        memory: 400Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi

prometheusOperator:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-operator
    tag: v0.61.1
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

  prometheusConfigReloader:
    image:
      registry: quay.io
      repository: prometheus-operator/prometheus-config-reloader
      tag: v0.61.1
      sha: ""
    resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi

kube-state-metrics:
  namespaceOverride: kubesphere-monitoring-system
  image:
    registry: docker.io
    repository: kubesphere/kube-state-metrics
    tag: v2.8.2
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: 10m
      memory: 190Mi
  kubeRBACProxy:
    image:
      registry: quay.io
      repository: brancz/kube-rbac-proxy
      tag: v0.14.0
    resources:
      limits:
        cpu: 40m
        memory: 40Mi
      requests:
        cpu: 20m
        memory: 20Mi


prometheus-node-exporter:
  namespaceOverride: kubesphere-monitoring-system
  image:
    registry: quay.io
    repository: prometheus/node-exporter
    tag: ""
  resources:
    limits:
      cpu: 250m
      memory: 180Mi
    requests:
      cpu: 102m
      memory: 180Mi
  kubeRBACProxy:
    image:
      registry: quay.io
      repository: brancz/kube-rbac-proxy
      tag: v0.14.0
    resources:
      limits:
        cpu: 40m
        memory: 40Mi
      requests:
        cpu: 20m
        memory: 20Mi

grafana:
  enabled: false
  namespaceOverride: kubesphere-monitoring-system
  # grafana does not support the global.imageRegistry
  image:
    repository: grafana/grafana
    tag: ""

  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 100Mi
  persistence:
    enabled: true
    type: "pvc"
    size: 50Mi

  sidecar:
    image:
      repository: quay.io/kiwigrid/k8s-sidecar
      tag: 1.24.6
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
  initChownData:
    image:
      repository: busybox
      tag: "1.31.1"
    resources:
      limits:
        cpu: 40m
        memory: 40Mi
      requests:
        cpu: 20m
        memory: 20Mi