apiVersion: v2
name: prometheus-node-exporter
description: A Helm chart for prometheus node-exporter
keywords:
  - node-exporter
  - prometheus
  - exporter
type: application
version: 4.21.8
appVersion: 1.6.0
home: https://github.com/prometheus/node_exporter/
sources:
  - https://github.com/prometheus/node_exporter/
maintainers:
  - email: gianrubio@gmail.com
    name: gianrubio
  - email: zanhsieh@gmail.com
    name: zanhsieh
  - email: rootsandtrees@posteo.de
    name: zeritti
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
dependencies:
- condition: ProcessExporter.enabled
  name: ProcessExporter
  repository: file://charts/prometheus-process-exporter
  version: 0.5.*
- condition: CalicoExporter.enabled
  name: CalicoExporter
  repository: file://charts/calico-exporter
  version: 0.3.*
