apiVersion: alerting.kubesphere.io/v2beta1
kind: GlobalRuleGroup
metadata:
  annotations:
    alerting.kubesphere.io/initial-configuration: '{"apiVersion":"alerting.kubesphere.io/v2beta1","kind":"GlobalRuleGroup","metadata":{"annotations":{},"labels":{"alerting.kubesphere.io/builtin":"true","alerting.kubesphere.io/enable":"true"},"name":"calico-bgp"},"spec":{"rules":[{"alert":"CalicoBGPBirdDown","annotations":{"description":"Calico BGP bird {{ $labels.instance }} ({{ $labels.router_id }}) is down.","runbook_url":"https://alert-runbooks.kubesphere.io/runbooks/calico/calicobgpbirddown","summary":"Calico BGP bird is down."},"expr":"calico_bgp_bird_info{up=\"false\"} == 1\n","for":"5m","labels":{"rule_id":"6a9f0b8a4c7e4c9d8f3b5a6c0d8f9e7b"},"severity":"critical"},{"alert":"CalicoBirdLastRebootTimestampChanged","expr":"increase(calico_bgp_bird_last_reboot_timestamp_seconds[5m]) > 1\n","labels":{"rule_id":"e7b8f9a6c0d8f3b7a6c0d8f9e7d9d6b4"},"severity":"warn","annotations":{"summary":"Calico BGP bird last reboot timestamp has changed.","description":"Calico BGP bird {{ $labels.instance }} ({{ $labels.router_id }}) last reboot timestamp has changed.","runbook_url":"https://alert-runbooks.kubesphere.io/runbooks/calico/calicobirdlastreboottimestampchanged"}},{"alert":"CalicoBGPPeerStateAbnormal","annotations":{"description":"Calico BGP peer {{ $labels.name }} ({{ $labels.ip }}) is not in established state.","runbook_url":"https://alert-runbooks.kubesphere.io/runbooks/calico/calicobgppeerstateabnormal","summary":"Calico BGP peer connection state is abnormal."},"expr":"calico_bgp_peer_info{conn_state!=\"Established\"} == 1\n","for":"5m","labels":{"rule_id":"8f7c4f0a9d6a4b0c9f3a7b8c6d7f8e9c"},"severity":"warning"},{"alert":"CalicoIPPoolUsageHigh","annotations":{"description":"Calico IP pool {{ $labels.name }} ({{ $labels.cidr }}) has {{ $value | humanizePercentage }} of IPs allocated.","runbook_url":"https://alert-runbooks.kubesphere.io/runbooks/calico/calicopoolusagehigh","summary":"Calico IP pool usage is high."},"expr":"calico_ippool_allocated_ips / calico_ippool_capacity >= 0.9\n","for":"5m","labels":{"rule_id":"a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2"},"severity":"warning"}]}}'
  labels:
    alerting.kubesphere.io/builtin: "true"
    alerting.kubesphere.io/enable: "true"
  name: calico-bgp
  namespace: kubesphere-monitoring-system
spec:
  rules:
    - alert: CalicoBGPBirdDown
      annotations:
        description: 'Calico BGP bird {{ $labels.instance }} ({{ $labels.router_id }}) is down.'
        runbook_url: https://alert-runbooks.kubesphere.io/runbooks/calico/calicobgpbirddown
        summary: Calico BGP bird is down.
      expr: |
        calico_bgp_bird_info{up="false"} == 1
      for: 5m
      labels:
        rule_id: 6a9f0b8a4c7e4c9d8f3b5a6c0d8f9e7b
      severity: critical
    - alert: CalicoBirdLastRebootTimestampChanged
      expr: increase(calico_bgp_bird_last_reboot_timestamp_seconds[5m]) > 5
      labels:
        rule_id: e7b8f9a6c0d8f3b7a6c0d8f9e7d9d6b4
      severity: warn
      annotations:
        summary: Calico BGP bird last reboot timestamp has changed.
        description: "Calico BGP bird {{ $labels.instance }} ({{ $labels.router_id }}) last reboot timestamp has changed."
        runbook_url: https://alert-runbooks.kubesphere.io/runbooks/calico/calicobirdlastreboottimestampchanged
    - alert: CalicoBGPPeerStateAbnormal
      annotations:
        description: 'Calico BGP peer {{ $labels.name }} ({{ $labels.ip }}) is not in established state.'
        runbook_url: https://alert-runbooks.kubesphere.io/runbooks/calico/calicobgppeerstateabnormal
        summary: Calico BGP peer connection state is abnormal.
      expr: |
        calico_bgp_peer_info{conn_state!="Established"} == 1
      for: 5m
      labels:
        rule_id: 8f7c4f0a9d6a4b0c9f3a7b8c6d7f8e9c
      severity: warning
    - alert: CalicoIPPoolUsageHigh
      annotations:
        description: 'Calico IP pool {{ $labels.name }} ({{ $labels.cidr }}) has {{ $value | humanizePercentage }} of IPs allocated.'
        runbook_url: https://alert-runbooks.kubesphere.io/runbooks/calico/calicopoolusagehigh
        summary: Calico IP pool usage is high.
      expr: |
        calico_ippool_allocated_ips / calico_ippool_capacity >= 0.9
      for: 5m
      labels:
        rule_id: a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2
      severity: warning